# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'exptool.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_ExposureTool(object):
    def setupUi(self, ExposureTool):
        if not ExposureTool.objectName():
            ExposureTool.setObjectName(u"ExposureTool")
        ExposureTool.resize(511, 471)
        ExposureTool.setMinimumSize(QSize(260, 100))
        ExposureTool.setMaximumSize(QSize(1000, 1000))
        font = QFont()
        font.setPointSize(8)
        ExposureTool.setFont(font)
        ExposureTool.setIconSize(QSize(15, 15))
        self.centralwidget = QWidget(ExposureTool)
        self.centralwidget.setObjectName(u"centralwidget")
        self.dewtemp_LcdNumber = QLCDNumber(self.centralwidget)
        self.dewtemp_LcdNumber.setObjectName(u"dewtemp_LcdNumber")
        self.dewtemp_LcdNumber.setGeometry(QRect(230, 270, 71, 23))
        self.camtemp_LcdNumber = QLCDNumber(self.centralwidget)
        self.camtemp_LcdNumber.setObjectName(u"camtemp_LcdNumber")
        self.camtemp_LcdNumber.setGeometry(QRect(130, 270, 71, 23))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 300, 451, 23))
        self.progressBar.setValue(24)
        self.testimage_CheckBox = QCheckBox(self.centralwidget)
        self.testimage_CheckBox.setObjectName(u"testimage_CheckBox")
        self.testimage_CheckBox.setGeometry(QRect(140, 90, 91, 20))
        self.imagetitle_LineEdit = QLineEdit(self.centralwidget)
        self.imagetitle_LineEdit.setObjectName(u"imagetitle_LineEdit")
        self.imagetitle_LineEdit.setGeometry(QRect(130, 150, 261, 22))
        self.messages_statusPlainTextEdit = QPlainTextEdit(self.centralwidget)
        self.messages_statusPlainTextEdit.setObjectName(u"messages_statusPlainTextEdit")
        self.messages_statusPlainTextEdit.setGeometry(QRect(10, 340, 461, 31))
        self.exposuretime_SpinBox = QDoubleSpinBox(self.centralwidget)
        self.exposuretime_SpinBox.setObjectName(u"exposuretime_SpinBox")
        self.exposuretime_SpinBox.setGeometry(QRect(240, 50, 81, 22))
        self.imagetype_ComboBox = QComboBox(self.centralwidget)
        self.imagetype_ComboBox.setObjectName(u"imagetype_ComboBox")
        self.imagetype_ComboBox.setGeometry(QRect(140, 50, 73, 22))
        self.imagetype_Label = QLabel(self.centralwidget)
        self.imagetype_Label.setObjectName(u"imagetype_Label")
        self.imagetype_Label.setGeometry(QRect(140, 30, 91, 16))
        self.camtemp_Label = QLabel(self.centralwidget)
        self.camtemp_Label.setObjectName(u"camtemp_Label")
        self.camtemp_Label.setGeometry(QRect(130, 250, 71, 16))
        self.exposuretime_Label = QLabel(self.centralwidget)
        self.exposuretime_Label.setObjectName(u"exposuretime_Label")
        self.exposuretime_Label.setGeometry(QRect(240, 30, 91, 16))
        self.dewtemp_Label = QLabel(self.centralwidget)
        self.dewtemp_Label.setObjectName(u"dewtemp_Label")
        self.dewtemp_Label.setGeometry(QRect(230, 250, 71, 16))
        self.imagetitleLabel = QLabel(self.centralwidget)
        self.imagetitleLabel.setObjectName(u"imagetitleLabel")
        self.imagetitleLabel.setGeometry(QRect(130, 130, 91, 16))
        self.numseq_SpinBox = QSpinBox(self.centralwidget)
        self.numseq_SpinBox.setObjectName(u"numseq_SpinBox")
        self.numseq_SpinBox.setGeometry(QRect(340, 50, 61, 22))
        self.numseq_label = QLabel(self.centralwidget)
        self.numseq_label.setObjectName(u"numseq_label")
        self.numseq_label.setGeometry(QRect(340, 30, 61, 16))
        self.buttons_splitter = QSplitter(self.centralwidget)
        self.buttons_splitter.setObjectName(u"buttons_splitter")
        self.buttons_splitter.setGeometry(QRect(11, 31, 91, 241))
        self.buttons_splitter.setOrientation(Qt.Vertical)
        self.expose_Button = QPushButton(self.buttons_splitter)
        self.expose_Button.setObjectName(u"expose_Button")
        self.buttons_splitter.addWidget(self.expose_Button)
        self.sequence_Button = QPushButton(self.buttons_splitter)
        self.sequence_Button.setObjectName(u"sequence_Button")
        self.buttons_splitter.addWidget(self.sequence_Button)
        self.filename_Button = QPushButton(self.buttons_splitter)
        self.filename_Button.setObjectName(u"filename_Button")
        self.buttons_splitter.addWidget(self.filename_Button)
        self.detector_Button = QPushButton(self.buttons_splitter)
        self.detector_Button.setObjectName(u"detector_Button")
        self.buttons_splitter.addWidget(self.detector_Button)
        self.reset_Button = QPushButton(self.buttons_splitter)
        self.reset_Button.setObjectName(u"reset_Button")
        self.buttons_splitter.addWidget(self.reset_Button)
        self.telescope_Button = QPushButton(self.buttons_splitter)
        self.telescope_Button.setObjectName(u"telescope_Button")
        self.buttons_splitter.addWidget(self.telescope_Button)
        self.preferences_Button = QPushButton(self.buttons_splitter)
        self.preferences_Button.setObjectName(u"preferences_Button")
        self.buttons_splitter.addWidget(self.preferences_Button)
        self.pause_splitter = QSplitter(self.centralwidget)
        self.pause_splitter.setObjectName(u"pause_splitter")
        self.pause_splitter.setGeometry(QRect(11, 381, 225, 23))
        self.pause_splitter.setOrientation(Qt.Horizontal)
        self.pause_Button = QPushButton(self.pause_splitter)
        self.pause_Button.setObjectName(u"pause_Button")
        self.pause_splitter.addWidget(self.pause_Button)
        self.resume_Button = QPushButton(self.pause_splitter)
        self.resume_Button.setObjectName(u"resume_Button")
        self.pause_splitter.addWidget(self.resume_Button)
        self.abort_Button = QPushButton(self.pause_splitter)
        self.abort_Button.setObjectName(u"abort_Button")
        self.pause_splitter.addWidget(self.abort_Button)
        ExposureTool.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExposureTool)

        QMetaObject.connectSlotsByName(ExposureTool)
    # setupUi

    def retranslateUi(self, ExposureTool):
        ExposureTool.setWindowTitle(QCoreApplication.translate("ExposureTool", u"ExpStatus", None))
#if QT_CONFIG(tooltip)
        ExposureTool.setToolTip(QCoreApplication.translate("ExposureTool", u"azcam exposure status", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        ExposureTool.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.testimage_CheckBox.setText(QCoreApplication.translate("ExposureTool", u"Test Image", None))
        self.imagetype_Label.setText(QCoreApplication.translate("ExposureTool", u"Image Type", None))
        self.camtemp_Label.setText(QCoreApplication.translate("ExposureTool", u"CamTemp", None))
        self.exposuretime_Label.setText(QCoreApplication.translate("ExposureTool", u"Exposure Time", None))
        self.dewtemp_Label.setText(QCoreApplication.translate("ExposureTool", u"DewTemp", None))
        self.imagetitleLabel.setText(QCoreApplication.translate("ExposureTool", u"Image Title", None))
        self.numseq_label.setText(QCoreApplication.translate("ExposureTool", u"Num Seq.", None))
        self.expose_Button.setText(QCoreApplication.translate("ExposureTool", u"Expose", None))
        self.sequence_Button.setText(QCoreApplication.translate("ExposureTool", u"Sequence", None))
        self.filename_Button.setText(QCoreApplication.translate("ExposureTool", u"Filename", None))
        self.detector_Button.setText(QCoreApplication.translate("ExposureTool", u"Detector", None))
        self.reset_Button.setText(QCoreApplication.translate("ExposureTool", u"Reset", None))
        self.telescope_Button.setText(QCoreApplication.translate("ExposureTool", u"Abort", None))
        self.preferences_Button.setText(QCoreApplication.translate("ExposureTool", u"Preferences", None))
        self.pause_Button.setText(QCoreApplication.translate("ExposureTool", u"Pause", None))
        self.resume_Button.setText(QCoreApplication.translate("ExposureTool", u"Resume", None))
        self.abort_Button.setText(QCoreApplication.translate("ExposureTool", u"Readout", None))
    # retranslateUi

